const ProductData = [
  {
    id: 1,
    title: "Queso tipo mozzarella",
    subtitle: "Tajado 500gr",
    image: "/images/Products/Queso_tipo_mozzarella-Tajado_500gr.png",
    category: "Quesos frescos",
    descriptionEs: "Light reducido en grasa.",
    descriptionEn: "Reduced fat.",
    ingredientsEs: "Leche fresca pasteurizada, sal, cuajo.",
    ingredientsEn: "Fresh pasteurized milk, salt, rennet.",
    price: 26900,
    rating: 5,
    timeLeft: 27,
    totalSales: 7479,
  },
  {
    id: 2,
    title: "Queso tipo mozzarella",
    subtitle: "Bloque 1000gr",
    image: "/images/Products/Queso_tipo_mozzarella-Bloque_1000gr.png",
    category: "Quesos frescos",
    descriptionEs: "Light reducido en grasa.",
    descriptionEn: "Reduced fat.",
    ingredientsEs: "Leche fresca pasteurizada, sal, cuajo.",
    ingredientsEn: "Fresh pasteurized milk, salt, rennet.",
    price: 34700,
    rating: 4.3,
    timeLeft: 23,
    totalSales: 9000,
  },
  {
    id: 3,
    title: "Queso tipo mozzarella",
    subtitle: "Tajado 500gr",
    image:
      "https://img1.wsimg.com/isteam/ip/5b09541d-59cc-411b-9a7c-ae9e907d575b/mozarella%20500%20g%202022%20Artelak%20.png",
    category: "Quesos frescos",
    descriptionEs: "Light reducido en grasa.",
    descriptionEn: "Reduced fat.",
    ingredientsEs: "Leche fresca pasteurizada, sal, cuajo.",
    ingredientsEn: "Fresh pasteurized milk, salt, rennet.",
    price: 26900,
    rating: 5,
    timeLeft: 27,
    totalSales: 7479,
  },
  {
    id: 4,
    title: "Queso tipo mozzarella",
    subtitle: "Tajado 500gr",
    image:
      "https://img1.wsimg.com/isteam/ip/5b09541d-59cc-411b-9a7c-ae9e907d575b/mozarella%20500%20g%202022%20Artelak%20.png",
    category: "Quesos frescos",
    descriptionEs: "Light reducido en grasa.",
    descriptionEn: "Reduced fat.",
    ingredientsEs: "Leche fresca pasteurizada, sal, cuajo.",
    ingredientsEn: "Fresh pasteurized milk, salt, rennet.",
    price: 26900,
    rating: 5,
    timeLeft: 27,
    totalSales: 7479,
  },
  {
    id: 5,
    title: "Queso tipo mozzarella",
    subtitle: "Tajado 500gr",
    image:
      "https://img1.wsimg.com/isteam/ip/5b09541d-59cc-411b-9a7c-ae9e907d575b/mozarella%20500%20g%202022%20Artelak%20.png",
    category: "Quesos frescos",
    descriptionEs: "Light reducido en grasa.",
    descriptionEn: "Reduced fat.",
    ingredientsEs: "Leche fresca pasteurizada, sal, cuajo.",
    ingredientsEn: "Fresh pasteurized milk, salt, rennet.",
    price: 26900,
    rating: 5,
    timeLeft: 27,
    totalSales: 7479,
  },
  {
    id: 6,
    title: "Queso tipo mozzarella",
    subtitle: "Tajado 500gr",
    image:
      "https://img1.wsimg.com/isteam/ip/5b09541d-59cc-411b-9a7c-ae9e907d575b/mozarella%20500%20g%202022%20Artelak%20.png",
    category: "Quesos frescos",
    descriptionEs: "Light reducido en grasa.",
    descriptionEn: "Reduced fat.",
    ingredientsEs: "Leche fresca pasteurizada, sal, cuajo.",
    ingredientsEn: "Fresh pasteurized milk, salt, rennet.",
    price: 26900,
    rating: 5,
    timeLeft: 27,
    totalSales: 7479,
  },
  {
    id: 7,
    title: "Queso tipo mozzarella",
    subtitle: "Tajado 500gr",
    image:
      "https://img1.wsimg.com/isteam/ip/5b09541d-59cc-411b-9a7c-ae9e907d575b/mozarella%20500%20g%202022%20Artelak%20.png",
    category: "Quesos frescos",
    descriptionEs: "Light reducido en grasa.",
    descriptionEn: "Reduced fat.",
    ingredientsEs: "Leche fresca pasteurizada, sal, cuajo.",
    ingredientsEn: "Fresh pasteurized milk, salt, rennet.",
    price: 26900,
    rating: 5,
    timeLeft: 27,
    totalSales: 7479,
  },
  {
    id: 8,
    title: "Queso tipo mozzarella",
    subtitle: "Tajado 500gr",
    image:
      "https://img1.wsimg.com/isteam/ip/5b09541d-59cc-411b-9a7c-ae9e907d575b/mozarella%20500%20g%202022%20Artelak%20.png",
    category: "Quesos frescos",
    descriptionEs: "Light reducido en grasa.",
    descriptionEn: "Reduced fat.",
    ingredientsEs: "Leche fresca pasteurizada, sal, cuajo.",
    ingredientsEn: "Fresh pasteurized milk, salt, rennet.",
    price: 26900,
    rating: 5,
    timeLeft: 27,
    totalSales: 7479,
  },
  {
    id: 9,
    title: "Queso tipo mozzarella",
    subtitle: "Tajado 500gr",
    image:
      "https://img1.wsimg.com/isteam/ip/5b09541d-59cc-411b-9a7c-ae9e907d575b/mozarella%20500%20g%202022%20Artelak%20.png",
    category: "Quesos frescos",
    descriptionEs: "Light reducido en grasa.",
    descriptionEn: "Reduced fat.",
    ingredientsEs: "Leche fresca pasteurizada, sal, cuajo.",
    ingredientsEn: "Fresh pasteurized milk, salt, rennet.",
    price: 26900,
    rating: 5,
    timeLeft: 27,
    totalSales: 7479,
  },
  {
    id: 10,
    title: "Queso tipo mozzarella",
    subtitle: "Tajado 500gr",
    image:
      "https://img1.wsimg.com/isteam/ip/5b09541d-59cc-411b-9a7c-ae9e907d575b/mozarella%20500%20g%202022%20Artelak%20.png",
    category: "Quesos frescos",
    descriptionEs: "Light reducido en grasa.",
    descriptionEn: "Reduced fat.",
    ingredientsEs: "Leche fresca pasteurizada, sal, cuajo.",
    ingredientsEn: "Fresh pasteurized milk, salt, rennet.",
    price: 26900,
    rating: 5,
    timeLeft: 27,
    totalSales: 7479,
  },
  {
    id: 11,
    title: "Queso tipo mozzarella",
    subtitle: "Tajado 500gr",
    image:
      "https://img1.wsimg.com/isteam/ip/5b09541d-59cc-411b-9a7c-ae9e907d575b/mozarella%20500%20g%202022%20Artelak%20.png",
    category: "Quesos frescos",
    descriptionEs: "Light reducido en grasa.",
    descriptionEn: "Reduced fat.",
    ingredientsEs: "Leche fresca pasteurizada, sal, cuajo.",
    ingredientsEn: "Fresh pasteurized milk, salt, rennet.",
    price: 26900,
    rating: 5,
    timeLeft: 27,
    totalSales: 7479,
  },
  {
    id: 12,
    title: "Queso tipo mozzarella",
    subtitle: "Tajado 500gr",
    image:
      "https://img1.wsimg.com/isteam/ip/5b09541d-59cc-411b-9a7c-ae9e907d575b/mozarella%20500%20g%202022%20Artelak%20.png",
    category: "Quesos frescos",
    descriptionEs: "Light reducido en grasa.",
    descriptionEn: "Reduced fat.",
    ingredientsEs: "Leche fresca pasteurizada, sal, cuajo.",
    ingredientsEn: "Fresh pasteurized milk, salt, rennet.",
    price: 26900,
    rating: 5,
    timeLeft: 27,
    totalSales: 7479,
  },
];
export default ProductData;
